questions = [
{"question": "Who won the 2018 Monaco Grand Prix?",
     "options": {"A": "Lewis Hamilton",
                 "B": "Kimi Raikkonen",
                 "C": "Daniel Ricciardo",
                 "D": "Sebastien Vettel"},
     "answer": "C"},

    {"question": "Which basketball team has attended the most\
        NBA grand finals?",
     "options": {"A": "Golden State Warriors",
                 "B": "Los Angeles Lakers",
                 "C": "Philadelphia 76ers",
                 "D": "Boston Celtics"},
     "answer": "B"},

    {"question": "Who won the Uefa Champions League in 1999?",
     "options": {"A": "Barcelona",
                 "B": "Liverpool",
                 "C": "Manchester United",
                 "D": "Bayern Munich"},
     "answer": "C"},

    {"question": "What national team won the 2016 edition of the \ UEFA European Championship?",
     "options": {"A": "Portugal",
                 "B": "Germany",
                 "C": "England",
                 "D": "France"},
     "answer": "A"},

    {"question": "Who was the top scorer of the 2014 FIFA World Cup?",
     "options": {"A": "Neymar ",
                 "B": "Lionel Messi",
                 "C": "Thomas Müller",
                 "D": "James Rodríguez"},
     "answer": "D"},

    {"question": "Who won the 2011 Stanley Cup?",
     "options": {"A": "New York Rangers",
                 "B": "Montreal Canadiens",
                 "C": "Boston Bruins",
                 "D": "Toronto Maple Leafs"},
     "answer": "C"},

    {"question": "Who was the topscorer for England national football team?",
     "options": {"A": "David Beckham",
                 "B": "Wayne Rooney",
                 "C": "Steven Gerrard",
                 "D": "Michael Owen"},
     "answer": "B"},

    {"question": "In Formula 1, the Virtual Safety Car was introduced following the fatal crash of which driver?",
     "options": {"A": "Jules Bianchi",
                 "B": "Ayrton Senna",
                 "C": "Ronald Ratzenberger",
                 "D": "Gilles Villeneuve"},
     "answer": "A"},

    {"question": "Which soccer team won the Copa America 2015 Championship?",
     "options": {"A": "Brazil",
                 "B": "Argentina",
                 "C": "Chile",
                 "D": "Paraguay"},
     "answer": "C"},

    {"question": "Which of the following Grand Slam tennis tournaments occurs LAST?",
     "options": {"A": "Wimbledon",
                 "B": "Australian Open",
                 "C": "French Open",
                 "D": "US Open"},
     "answer": "D"},

    {"question": "Which golfer won the the 2019 Masters tournament?",
     "options": {"A": "Bubba Watson",
                 "B": "Tiger Woods",
                 "C": "Rory McIllroy",
                 "D": "Phil Mickelson"},
     "answer": "B"},

     {"question": "Which country is hosting the 2022 FIFA World Cup?",
     "options": {"A": "Quatar",
                 "B": "Uganda",
                 "C": "Vietnam",
                 "D": "Bolivia"},
     "answer": "A"},
]
